Running on NVIDIA TITAN Xp with 12.58 GB of VRAM.
Traceback (most recent call last):
  File "/home/users/dansun/toric-decoder/main.py", line 62, in <module>
    decoder_2D(state, T, c, Î·, p_error)
  File "/home/users/dansun/toric-decoder/toric.py", line 141, in decoder_2D
    state.add_errors(p_error)
  File "/home/users/dansun/toric-decoder/toric.py", line 65, in add_errors
    errors = (rng.random(self.dims, dtype = cp.float32) < p_error).astype(cp.uint8)
  File "cupy/random/_generator_api.pyx", line 160, in cupy.random._generator_api.Generator.random
  File "cupy/_core/core.pyx", line 516, in cupy._core.core._ndarray_base.astype
  File "cupy/_core/core.pyx", line 575, in cupy._core.core._ndarray_base.astype
  File "cupy/_core/core.pyx", line 136, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 224, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 742, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1419, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1440, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1120, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1141, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1379, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 2,013,280,256 bytes (allocated so far: 12,091,969,536 bytes).
